### ISSUE TITLE
burp插件加载失败？

### ISSUE THREAD

**Issue by emmnoi** [ztosec/secscan-authcheck#10]
在burp extension 中加载jar 包 失败
java.lang.ClassNotFoundException: burp.BurpExtender
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at burp.sue.a(Unknown Source)
	at burp.sue.<init>(Unknown Source)
	at burp.mn.a(Unknown Source)
	at burp.ooh.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by xiaoxiaoxu203** [comment]
java.lang.ClassNotFoundException: burp.BurpExtender
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at burp.a3_.a(Unknown Source)
	at burp.a3_.<init>(Unknown Source)
	at burp.gcg.a(Unknown Source)
	at burp.ao3.lambda$panelLoaded$0(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
